### ISSUE TITLE
thumbnails are sometimes rotate incorrectly

### ISSUE THREAD

**Issue by zachjs** [aarongut/fincom2#2]
It seems that the rendered thumbnails do not preserve the EXIF data from the original. The fix given in https://github.com/codingjoe/django-stdimage/issues/66 seems reasonable, but I'm not set up to test.

**Comment by aarongut** [comment]
Even if they did include EXIF, most browsers don't respect the image rotation when displayed in the DOM, only when viewing full-screen. I'll look at that thumbnailing code.

**Comment by aarongut** [comment]
Fixed as of https://github.com/aarongut/fincom2/commit/d85c53c6888d9e6a25cb46dcfe4ba80bd1ca0b11
